#!/bin/sh

# check that DATA_DIR env is set, if not exit
if [ -z "$DATA_DIR" ]; then
  echo "DATA_DIR env not set, exiting"
  exit 1
fi

# check that SEED_NODES env is set, if not exit 
if [ -z "$SEED_NODES" ]; then
  echo "SEED_NODES env not set, exiting"
  exit 1
fi

# check that genesis.json exists in DATA_DIR if not copy it
if [ ! -f "$DATA_DIR/config/genesis.json" ]; then
  echo "config files not found, copying over"
  mkdir -p $DATA_DIR/config
  cp /app/data/config/* $DATA_DIR/config/
fi

echo "Running RPC node"
lavad start --home=$DATA_DIR --p2p.seeds $SEED_NODES
