#!/bin/sh

# check that DATA_DIR env is set, if not exit
if [ -z "$DATA_DIR" ]; then
  echo "DATA_DIR env not set, exiting"
  exit 1
fi

# check that SEED_NODES env is set, if not exit 
if [ -z "$SEED_NODES" ]; then
  echo "SEED_NODES env not set, exiting"
  exit 1
fi

# setup env vars for cosmovisor
export DAEMON_NAME="lavad"
export DAEMON_HOME=$DATA_DIR
export DAEMON_ALLOW_DOWNLOAD_BINARIES="true"
export DAEMON_LOG_BUFFER_SIZE="512"
export DAEMON_RESTART_AFTER_UPGRADE="true"
export UNSAFE_SKIP_BACKUP="true"

# check that genesis.json exists in DATA_DIR if not copy it
if [ ! -f "$DATA_DIR/config/genesis.json" ]; then
  echo "config files not found, copying over, this will only happen once"
  echo "data dir is $DATA_DIR"

  mkdir -p $DATA_DIR/config
  cp /app/data/config/* $DATA_DIR/config/

  mkdir -p $DATA_DIR/data
  cosmovisor init $(which lavad)
fi

echo "Running RPC node"
cosmovisor run start --home=$DATA_DIR --p2p.seeds $SEED_NODES
